parameter_defaults:
  CephAnsibleDisksConfig:
    devices:
      - /dev/vdb
      - /dev/vdc
    dedicated_devices:
      - /dev/vdd
      - /dev/vdd
    osd_scenario: non-collocated
    osd_objectstore: filestore
  CephPoolDefaultPgNum: 32
  CephPoolDefaultSize: 2
  CephAnsiblePlaybookVerbosity: 1
  CephAnsibleExtraConfig:
    osd_recovery_op_priority: 1
    osd_recovery_max_active: 1
    osd_max_backfills: 1
    is_hci: true
    ceph_osd_docker_cpu_limit: 2
  ManilaCephFSDataPoolPGNum: 32
  ManilaCephFSMetadataPoolPGNum: 32
